### ISSUE TITLE
Captcha as a service

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Celtic68/grbUniformOrdering#2]
@Celtic68 Good job keeping up with your weekly reflections!  Reading through your comments  reminded me to look into the captcha implementation. Looks like this one can be implemented using some java code... https://www.journaldev.com/7133/how-to-integrate-google-recaptcha-in-java-web-application.

**Comment by Celtic68** [comment]
Thanks very much!  I think I have settled on captcha, email, and that zip code service you mentioned for this project.  If I get far enough ahead, I may look at trying some kind of baseball ticker.  But, that is a dream task...  :)

**Comment by Celtic68** [comment]
Going to table the captcha for now - using zip code validation service, our team project service to search for an existing user name and validate the email. If time allows, I will also get in the java email service.

**Comment by Celtic68** [comment]
Captcha page bookmarked for future release study
