### ISSUE TITLE
Instructor Feedback - Week 5

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Celtic68/grbUniformOrdering#3]
Nice job with the early finish on week 5 and implementing that generic dao already. 

- [x] If the user is deleted, is the role also deleted properly? Might be good to have a test case to confirm this. Is there reason to test what happens if the role is deleted?  https://github.com/Celtic68/grbUniformOrdering/blob/c226887cf81b19a15837a07079b00f1274b240a1/test/java/com/joealexanderIII/dao/UserDaoTest.java#L116-L121
- [x] We were talking about these two methods last night, and now looking at them, I think you may be able to get down to just a single method. https://github.com/Celtic68/grbUniformOrdering/blob/c226887cf81b19a15837a07079b00f1274b240a1/src/main/java/com/joealexanderIII/dao/GenericDao.java#L63 and https://github.com/Celtic68/grbUniformOrdering/blob/c226887cf81b19a15837a07079b00f1274b240a1/src/main/java/com/joealexanderIII/dao/GenericDao.java#L87.
Could those be replaced with something like `public T getByPropertyWithNumberUniqueEqual(String propertyName, Object value) {`

**Comment by Celtic68** [comment]
1. Thanks for catching that - I updated the delete test in the UserDaoTest class to account for that condition.

2. Great idea!  I never thought about trying that - made that change and it works great!

3. I am still working on the tests for Player and UniformOrder - I thought that setting up the annotations for all and then doing the testing for the User model was all that was needed for the week 5 exercise. You didn't overlook anything - all those crud methods will exist for Player and UniformOrder. I will have the Player and UniformOrder tests done tomorrow.

**Comment by Celtic68** [comment]
All the unit tests are complete and ready to go (I believe).  I had a couple edge test cases I created for the UniformOrder model that are fairly involved - I would like to touch base on those when we can just to see if I should have done something differently.

**Comment by pawaitemadisoncollege** [comment]
Just took a look - a couple of those methods do look involved - let's chat more in person so I'm sure that I understand the intent!
