### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by LeeYang2019** [Celtic68/grbUniformOrdering#5]
# Design/Code Review 1

### Reviewer:Lee Yang

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| A very cool and practical solution to an every day problem. You did a great job presenting the problem and discussing how you were going to address it. I really like the idea of an email roller (not sure if I captured that correctly) to send an email and notify whomever that an order has been submitted. I don't recall if you had mentioned this but regarding adding other features, such as a captcha, I would hope you are saving them for a later phase in your application. Of course, that is assuming you are running out of time. I don't feel they are necessary to this phase of the project. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Great use of flowcharts to walk us through your application. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| I can tell a lot of thought went into your database design.  You did a great job structuring it.|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | We didn't do much code review but having glossed over your code afterwards, you did a great job writing them. There are no system.out.println() lines, which is good, and your code is clean and easy to follow.|

**Comment by pawaitemadisoncollege** [comment]
@LeeYang2019  - looks like your review for Julie snuck in here - can you fix please?

**Comment by LeeYang2019** [comment]
> @LeeYang2019 - looks like your review for Julie snuck in here - can you fix please?

Sorry about that. This has been updated.

**Comment by Celtic68** [comment]
Thanks for the feedback Lee!
